
SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";

CREATE TABLE IF NOT EXISTS `chitiethoadon` (
  `MAHD` int(11) NOT NULL,
  `MASANPHAM` int(11) NOT NULL,
  `DONGIA` bigint(20) DEFAULT NULL,
  `SOLUONG` int(11) DEFAULT NULL,
  `TONGITEN` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`MAHD`,`MASANPHAM`),
  KEY `FK_CHITIETHOADON_SANPHAM` (`MASANPHAM`),
  KEY `FK_CHITIETHOADON_HD` (`MAHD`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

DELIMITER $$
CREATE TRIGGER `trg_chitiethoadon` BEFORE INSERT ON `chitiethoadon` FOR EACH ROW UPDATE sanpham SET SOLUONG = SOLUONG - new.SOLUONG 
    WHERE MASANPHAM = new.MASANPHAM
$$
DELIMITER ;

CREATE TABLE IF NOT EXISTS `hoadon` (
  `MAHD` int(11) NOT NULL AUTO_INCREMENT,
  `MAKH` varchar(10) DEFAULT NULL,
  `TONGTIEN` bigint(20) DEFAULT NULL,
  `NGAYLAPHOADON` date DEFAULT NULL,
  PRIMARY KEY (`MAHD`),
  KEY `FK_HOADON_KHACHHANG` (`MAKH`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=65 DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `khachhang` (
  `USERNAME` varchar(10) NOT NULL,
  `TENKH` varchar(100) DEFAULT NULL,
  `MATKHAU` varchar(100) DEFAULT NULL,
  `DIACHI` varchar(100) DEFAULT NULL,
  `SODT` int(11) DEFAULT NULL,
  `HINHANH` char(100) DEFAULT NULL,
  PRIMARY KEY (`USERNAME`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `sanpham` (
  `MASANPHAM` int(11) NOT NULL AUTO_INCREMENT,
  `TENSANPHAM` varchar(200) DEFAULT NULL,
  `GIATIEN` bigint(20) DEFAULT NULL,
  `SOLUONG` int(11) DEFAULT NULL,
  `GIATIENKHUYENMAI` bigint(20) DEFAULT NULL,
  `MOTA` varchar(500) DEFAULT NULL,
  `HINHANH` varchar(100) DEFAULT NULL,
  `NGAYCAPNHAT` date DEFAULT NULL,
  `MALSANPHAM` int(11) DEFAULT NULL,
  PRIMARY KEY (`MASANPHAM`),
  KEY `FK_SANPHAM_LOAISANPHAM` (`MALSANPHAM`)
) ENGINE=InnoDB AUTO_INCREMENT=65 DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `loaisanpham` (
  `MALSANPHAM` int(11) NOT NULL AUTO_INCREMENT,
  `TENLSANPHAM` varchar(20) DEFAULT NULL,
  `HINHANH` char(100) DEFAULT NULL,
  PRIMARY KEY (`MALSANPHAM`)
) ENGINE=InnoDB AUTO_INCREMENT=65 DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `nhanvien` (
  `MANV` varchar(100) NOT NULL,
  `MATKHAU` varchar(100),
  `HOTEN` varchar(20) DEFAULT NULL,
  `GIOITINH` varchar(3) DEFAULT NULL,
  `NGAYSINH` date DEFAULT NULL,
  `DIACHI` varchar(30) DEFAULT NULL,
  `SODT` int(11) DEFAULT NULL,
  PRIMARY KEY (`MANV`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

ALTER TABLE `chitiethoadon`
  ADD CONSTRAINT `FK_CHITIETHOADON_SANPHAM` FOREIGN KEY (`MASANPHAM`) REFERENCES `sanpham` (`MASANPHAM`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  ADD CONSTRAINT `FK_CTHD_HOADON` FOREIGN KEY (`MAHD`) REFERENCES `hoadon` (`MAHD`),
  ADD CONSTRAINT `chitiethoadon_ibfk_1` FOREIGN KEY (`MAHD`) REFERENCES `hoadon` (`MAHD`);

ALTER TABLE `hoadon`
  ADD CONSTRAINT `FK_HOADON_KHACHHANG` FOREIGN KEY (`MAKH`) REFERENCES `khachhang` (`USERNAME`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  ADD CONSTRAINT `hoadon_ibfk_1` FOREIGN KEY (`MAKH`) REFERENCES `khachhang` (`USERNAME`);

ALTER TABLE `sanpham`
  ADD CONSTRAINT `FK_SANPHAM_LOAISANPHAM` FOREIGN KEY (`MALSANPHAM`) REFERENCES `loaisanpham` (`MALSANPHAM`) ON DELETE NO ACTION ON UPDATE NO ACTION;
COMMIT;
